services:
  api:
    build:
      context: ./API
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    # depends_on:
    #   - postgres
    #   - redis

  worker:
    build:
      context: ./Worker
      dockerfile: DockerFile
    # depends_on:
    #   - redis


  postgres:
    image: postgres:18beta3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # redis:
  #   image: redis:latest
  #   restart: always
  dragonfly:                                                                                                                                    
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'                                                                                        
    ulimits:
      memlock: -1
      
  # beat:
  #   build:
  #     context: ./BackEnd/API/celery
  #     dockerfile: Dockerfile_beat
  #   volumes:
  #     - ./BackEnd/API/celery:/app
  #   depends_on:
  #     - redis
  #     - task_agent

volumes:
  postgres_data: