FROM ghcr.io/astral-sh/uv:bookworm-slim AS builder

ENV UV_PYTHON_INSTALL_DIR=/python
ENV UV_PYTHON_PREFERENCE=only-managed
ENV UV_COMPILE_BYTECODE=1 
ENV UV_LINK_MODE=copy

RUN uv python install 3.11

WORKDIR /API

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-dev

COPY . /API

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-dev

FROM gcr.io/distroless/cc-debian12

WORKDIR /API

USER nonroot

COPY --from=builder /python /python
COPY --from=builder /API /API

ENV PATH="/API/.venv/bin:/python/bin:$PATH"

CMD ["fastapi", "run", "--host", "0.0.0.0", "--port", "8000"]
